package util

// from: https://github.com/DefectDojo/django-DefectDojo/blob/b08723ded1491d82910e51810de27963ee6ccca2/dojo/tools/factory.py

var SupportedReportTypes = map[string]bool{
	"Burp Scan":                    false,
	"Burp Enterprise Scan":         false,
	"Nessus Scan":                  false,
	"Clair Scan":                   false,
	"Nmap Scan":                    false,
	"Nikto Scan":                   false,
	"Nexpose Scan":                 false,
	"Veracode Scan":                true,
	"Checkmarx Scan":               false,
	"Checkmarx Scan detailed":      false,
	"Contrast Scan":                false,
	"Crashtest Security JSON File": false,
	"Crashtest Security XML File":  false,
	"Bandit Scan":                  false,
	"ESLint Scan":                  false,
	"ZAP Scan":                     true,
	"AppSpider Scan":               false,
	"Arachni Scan":                 false,
	"VCG Scan":                     false,
	"Dependency Check Scan":        false,
	"Dependency Track Finding Packaging Format (FPF) Export": false,
	"Retire.js Scan":                          false,
	"Node Security Platform Scan":             false,
	"NPM Audit Scan":                          false,
	"PHP Symfony Security Check":              false,
	"Generic Findings Import":                 false,
	"Qualys Scan":                             false,
	"Qualys Infrastructure Scan (WebGUI XML)": false,
	"Qualys Webapp Scan":                      false,
	"OpenVAS CSV":                             false,
	"Snyk Scan":                               false,
	"SKF Scan":                                false,
	"SSL Labs Scan":                           false,
	"Trufflehog Scan":                         false,
	"Clair Klar Scan":                         false,
	"Gosec Scanner":                           false,
	"Trustwave Scan (CSV)":                    false,
	"PHP Security Audit v2":                   false,
	"Acunetix Scan":                           false,
	"Fortify Scan":                            false,
	"SonarQube Scan":                          false,
	"SonarQube Scan detailed":                 false,
	"SonarQube API Import":                    false,
	"MobSF Scan":                              false,
	"AWS Scout2 Scan":                         false,
	"AWS Prowler Scan":                        false,
	"Brakeman Scan":                           false,
	"SpotBugs Scan":                           false,
	"Safety Scan":                             false,
	"DawnScanner Scan":                        false,
	"Anchore Engine Scan":                     false,
	"Bundler-Audit Scan":                      false,
	"Twistlock Image Scan":                    false,
	"IBM AppScan DAST":                        false,
	"Kiuwan Scan":                             false,
	"Blackduck Hub Scan":                      false,
	"Blackduck Component Risk":                false,
	"Sonatype Application Scan":               false,
	"Openscap Vulnerability Scan":             false,
	"Immuniweb Scan":                          false,
	"Wapiti Scan":                             false,
	"Cobalt.io Scan":                          false,
	"Mozilla Observatory Scan":                false,
	"Whitesource Scan":                        false,
	"Microfocus Webinspect Scan":              false,
	"Wpscan":                                  false,
	"Sslscan":                                 false,
	"JFrog Xray Scan":                         false,
	"Sslyze Scan":                             false,
	"SSLyze 3 Scan (JSON)":                    false,
	"Testssl Scan":                            false,
	"Hadolint Dockerfile check":               false,
	"Aqua Scan":                               false,
	"HackerOne Cases":                         false,
	"Xanitizer Scan":                          false,
	"Trivy Scan":                              false,
	"Outpost24 Scan":                          false,
	"DSOP Scan":                               false,
	"Anchore Enterprise Policy Check":         false,
	"Gitleaks Scan":                           false,
	"Harbor Vulnerability Scan":               false,
	"Github Vulnerability Scan":               false,
	"Choctaw Hog Scan":                        false,
	"GitLab SAST Report":                      false,
	"GitLab Dependency Scanning Report":       false,
	"Yarn Audit Scan":                         false,
	"BugCrowd Scan":                           false,
	"HuskyCI Report":                          false,
	"CCVS Report":                             false,
	"AWS Security Hub Scan":                   false,
	"Semgrep JSON Report":                     false,
	"Risk Recon API Importer":                 false,
	"DrHeader JSON Importer":                  false,
	"Checkov Scan":                            false,
	"kube-bench Scan":                         false,
	"ORT evaluated model Importer":            false,
	"SARIF":                                   false,
}
